During package installation there is no test for /opt/dbspace existence.
[Issue#]        N/A
[Bug/Feature]   When creating databse from scratch during depedencies
                installation for gbs build process error occurs:
                Error: unable to open database "/opt/dbspace/.rules-db.db3":
                unable to open database file.
[Cause]         Missing /opt/dbspace directory.
[Solution]      Add checking for /opt/dbspace existence. Create directory
                if missing.
[Verification]  Delete /opt/dbspace, install libprivilege-control, check if
                /opt/dbspace and "/opt/dbspace/.rules-db.db3" exists.

Change-Id: I216b75caf63ac69d08b0d3b07981860606dcb6b8

Conflicts:

	packaging/libprivilege-control.spec